### ISSUE TITLE
Want to work on Bayesian Benchmarking

### ISSUE THREAD

**Issue by sparkingdark** [stan-dev/design-docs#39]
Hey,
Myself Debojyoti a cs prefinal year student hope to participate in gsoc 2021 and I found this project quite interesting to implement https://github.com/stan-dev/design-docs/blob/master/gsoc_proposals/2021/bayesian_benchmarking.md

can you guys help me to getting start @mike-lawrence @MansMeg

**Comment by rok-cesnovar** [comment]
Hi @sparkingdark,
glad you are interested! Please write in the https://discourse.mc-stan.org/t/gsoc-2021-q-a-thread/21261

Thanks!
