### ISSUE TITLE
Should the process follow more closely with Rusts RFCs?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/design-docs#9]
I know this is a stan flavored version of the Rust RFC, but why don't we have the "motion for final comment" period and the subteam voting schema?

From the [Rust RFC](https://github.com/rust-lang/rfcs#what-the-process-is)

> At some point, a member of the subteam will propose a "motion for final comment period" (FCP), along with a disposition for the RFC (merge, close, or postpone).

>    This step is taken when enough of the tradeoffs have been discussed that the subteam is in a position to make a decision. That does not require consensus amongst all participants in the RFC thread (which is usually impossible). However, the argument supporting the disposition on the RFC needs to have already been clearly articulated, and there should not be a strong consensus against that position outside of the subteam. Subteam members use their best judgment in taking this step, and the FCP itself ensures there is ample time and notification for stakeholders to push back if it is made prematurely.
>    For RFCs with lengthy discussion, the motion to FCP is usually preceded by a summary comment trying to lay out the current state of the discussion and major tradeoffs/points of disagreement.
>    Before actually entering FCP, all members of the subteam must sign off; this is often the point at which many subteam members first review the RFC in full depth.

Is the voting stuff we are currently talking about on discourse going to be used instead of the subteam model Rust uses or is that for other things?

It feels like a good idea to have a way to formalize a final vote of "We are doing this feature"

**Comment by seantalts** [comment]
This is a great idea. I need to look more into ito as far as answering your
question. I'm not sure if it existed at the time. If it did, I was also
reading a lot about people's open complaints about the rust RFC system and
noting places where it seemed they needed to do certain extra bits of
process due to the Rust project's size (I think it's a few orders of
magnitude larger than Stan). Let me research it a little more and get back
to you.

**Comment by SteveBronder** [comment]
Word! Yeah I'm fine with things being a bit more loosey-goosey now, once we implement a system deprecating or changing it will be a lot harder
